ayomi_auth/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from .views import *

urlpatterns = [
    url(r'^login/',  auth_views.login,{'template_name':'ayomi_auth/login.html'}, name='login'),
    url(r'^logout/',  auth_views.logout, {'next_page':reverse_lazy('login')}, name='logout'),
    url(r'^register/', RegisterView.as_view(), name='register'),
    url(r'^profile/', login_required(ProfileView.as_view()), name='profile'),
    url(r'^update_email/', login_required(UpdateEmail.as_view()), name='update_email'),
]

ayomi_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.http.response import HttpResponse
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('ayomi_auth.urls')),
    url(r'^$', RedirectView.as_view(url='/login/')),
]

ayomi_auth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm



class UserForm(UserCreationForm):
    first_name = forms.CharField(max_length=50, label="prenom")
    last_name = forms.CharField(max_length=50, label="nom")
    email = forms.EmailField()

ayomi_auth/views.py
from django.contrib.auth import login, authenticate, get_user_model
from django.core.urlresolvers import reverse_lazy
from django.http.response import JsonResponse
from django.views.generic import FormView, DetailView
from django.contrib.auth.models import User
from django.views.generic.edit import UpdateView

from .forms import UserForm


class RegisterView(FormView):
    template_name = 'ayomi_auth/register.html'
    form_class = UserForm
    success_url = reverse_lazy('profile')
    def form_valid(self, form):
        user = User.objects.create_user(username=form.cleaned_data['username'], email=form.cleaned_data['email'], password=form.clean_password2(),
                                        first_name =form.cleaned_data['first_name'], last_name = form.cleaned_data['last_name'])
        user = authenticate(username=user.username, password=form.clean_password2())
        login(self.request, user)
        return super(RegisterView, self).form_valid(form)


class ProfileView(DetailView):
    model = get_user_model()
    template_name = 'ayomi_auth/profile.html'
    def get_object(self, queryset=None):
        return self.model.objects.get(pk=self.request.user.pk)


class UpdateEmail(UpdateView):
    model = get_user_model()
    fields = ['email']
    success_url = reverse_lazy('profile')

    def get_object(self, queryset=None):
        return self.model.objects.get(pk=self.request.user.pk)
    def post(self, request, *args, **kwargs):
        super(UpdateEmail, self).post(request, *args, **kwargs)
        return JsonResponse({"email":self.object.email})

ayomi_auth/templates/ayomi_auth/login.html
{% extends "base.html" %}

{% block content %}


    <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
        <div class="form-group col-md-6 col-md-offset-3">
            {% csrf_token %}
            <p><label for="username">Nom d'utilisateur</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Nom d'utilisateur"></p>

           <p><label for="password">Mot de passe</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Mot de passe"></p>
           <p><input type="submit" class="btn btn-primary" value="connexion"/>
            </p>

        </div>
    </form>


{% endblock %}

ayomi_auth/templates/ayomi_auth/profile.html
{% extends 'base.html' %}

{% block content %}

    <div>
        <h3>Nom d'utilisateur: {{ object }}</h3>
        <h3>Prénom: {{ object.first_name }}</h3>
        <h3>Nom: {{ object.last_name }}</h3>
        <h3>Email: <span id="email">{{ object.email }}</span></h3>
    </div>




    <button id="edit-email-btn" type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#email_modal">
        Modifier
    </button>



    <div class="modal fade" tabindex="-1" role="dialog" id="email_modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Modifier email</h4>
                </div>
                <form id="update-email" method="POST" action="{% url 'update_email' %}">
                    <div class="modal-body">
                        {% csrf_token %}
                        <input type="email" id="new-email" name="email" class="input-sm form-control" value="{{ object.email }}"/>
                    </div>
                    <div class="modal-footer">
                        <button id="close-btn" type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
                        <button id="save-btn" type="submit" class="btn btn-primary">Enregistrer</button>
                    </div>
                </form>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
{% endblock %}

ayomi_auth/templates/ayomi_auth/register.html
{% extends "base.html" %}

{% block content %}

    <!--{% if form.errors %}-->
        <!--{{form.errors}}-->
        <!--{% endif %}-->

    <form method="post" action="">
        <div class="form-group col-md-6 col-md-offset-3 ">
            {% csrf_token %}
            <p><label for="id_username">Nom d'utilisateur :</label>
                <input class="form-control" id="id_username" maxlength="30" name="username" type="text"/>
            </p>
            <p><label for="id_password1">Mot de passe :</label>
                <input class="form-control" id="id_password1" name="password1" type="password"/>
            </p>
            <p><label for="id_password2">Confirmation du mot de passe :</label>
                <input class="form-control" id="id_password2" name="password2" type="password"/>
            </p>
            <p><label for="id_first_name">prenom :</label>
                <input class="form-control" id="id_first_name" maxlength="50" name="first_name" type="text"/>
            </p>
            <p><label for="id_last_name">nom :</label>
                <input class="form-control" id="id_last_name" maxlength="50" name="last_name" type="text"/>
            </p>
            <p><label for="id_email">Email :</label>
                <input class="form-control" id="id_email" name="email" type="email"/>
            </p>
            <input type="submit" class="btn btn-primary" value="inscription"/>
        </div>
    </form>

{% endblock %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ayomi</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-dkTxiR4Mv8i0ubTj0fsgTCmhYmOtrc0o6rdrEO6hDZs9cAifak0Y2VVL2cecWHLQ" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Ayomi</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}">Déconnexion</a></li>
                {% else %}
                    <li><a href="{% url 'register' %}">Inscription</a></li>
                    <li><a href="{% url 'login' %}">Connexion</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="container">
    {% block content %}

    {% endblock %}
</div>
</body>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js" integrity="sha384-Zzs5x1/YUvlxpCu06c197tRCubLCMA7pCoHbZeoZuz/oEgYD6NVmvLzDSKYBoc3J" crossorigin="anonymous"></script>
<script src="{% static 'js/script.js' %}"></script>

</html>